# Site settings
title: techMango
description: 'a programming and data blog for the novice and veteran alike'
url: 'https://github.com/chrisgravatt/chrisgravatt.github.io'
# baseurl: '/blog'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Chris Gravatt'
  email: chrisgravatt@gmail.com
  twitter_username: 
  facebook_username: 
  github_username:  chrisgravatt
  linkedin_username:  christopher-gravatt-64550395


defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
# permalink: /blog/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
